### ISSUE TITLE
 Few questions about Multi_LiCa

### ISSUE THREAD

**Issue by af-doom** [TUMFTM/Multi_LiCa#10]
Hello, thank you for your great open source work. I have a few questions as follows: (1) Does it support multi-lidar calibration without overlapping fields of view? (2) Does it support various types of lidar (repeated and non-repeated scanning)?

**Comment by ga58lar** [comment]
Hi @af-doom,
(1) It does not support non-overlapping FOVs. An overlapping FOV is essential for the method. 
(2) It was evaluated on [HeLiPR](https://sites.google.com/view/heliprdataset), which is a dataset specifically designed to evaluate algorithms on different LiDARs.
