### ISSUE TITLE
Multi-LiDAR Calibration with Non-Overlapping Fields of View

### ISSUE THREAD

**Issue by af-doom** [TUMFTM/Multi_LiCa#11]
Hello, thank you very much for open-sourcing this valuable work. I have a few questions for you: 1) How much overlap is needed between different lasers? 2) What suggestions do you have for LiDAR calibration without overlapping fields of view?

**Comment by ga58lar** [comment]
Related to #10 

Hey @af-doom,
I appreciate your interest in our work.

I cannot give you a general valid number for the percentage of overlap. You can check our [paper](https://portal.fis.tum.de/en/publications/multi-lica-a-motion-and-targetless-multi-lidar-to-lidar-calibrati) and the included examples there. 

We are currently working on a method for non-overlapping sensors. Stay tuned and follow [TUMFTM](https://github.com/TUMFTM) to not miss the release.
