### ISSUE TITLE
base_link to lidar1 tf in quaternions? 

### ISSUE THREAD

**Issue by anuraj-rp** [TUMFTM/Multi_LiCa#3]
Hi,

Is it possible to specify the transform between base_link and lidars as quaternions in the config param yaml file?

**Comment by ga58lar** [comment]
Hey @anuraj-rp,
the to-base calibration is quite limited and will only compensate roll, pitch and z height of the alignment. It will compensate for a z offset with [base_to_ground_z ](https://github.com/TUMFTM/Multi_LiCa/blob/main/config/params.yaml#L31). The rest is directly calculated and does not need any input.  
You have to transform the result for x, y and yaw afterwards. We do not provide the input for these values in quaternion or rpy.
  
For the LiDAR-to-LiDAR calibration, we only take [deg] or [rad] as input, as it is only needed as a coarse initial guess and these are more intuitive than quaternions.
