### ISSUE TITLE
128 scans lidar and 32 scans lidar calibare

### ISSUE THREAD

**Issue by pedestrain123** [TUMFTM/Multi_LiCa#8]
Hello, may I ask if this algorithm can be used for joint calibration of external parameters between high-resolution LiDAR and low resolution LiDAR? For example, how accurate is the calibration of 128 line LiDAR and 32 line LiDAR?

**Comment by ga58lar** [comment]
Hi @pedestrain123,
we tested our algorithm on the [HeLiPr dataset](https://sites.google.com/view/heliprdataset), which consists of a similar configuration as you describe. We are on par with other methods and close to the GT, but it has to be mentioned that we found scenes where the GT was not correct by visually inspecting the transformed point clouds (We will release a paper on the algorithm and results soon).
![image](https://github.com/user-attachments/assets/3b76cece-d5ee-474c-bc9d-e0d0fe8b2773)

**Comment by pedestrain123** [comment]
> 你好[@pedestrain123](https://github.com/pedestrain123)[我们在HeLiPr 数据](https://sites.google.com/view/heliprdataset) 集上测试了我们的算法，该数据集的配置与您描述的类似。我们的结果与其他方法相当，并且接近 GT，但需要指出的是，我们通过目视检查转换后的点云发现了 GT 不正确的场景（我们将很快发布一篇关于该算法和结果的论文）。[](https://sites.google.com/view/heliprdataset) ![image](https://github.com/user-attachments/assets/3b76cece-d5ee-474c-bc9d-e0d0fe8b2773)

Do you have any plans to do target-free external parameter calibration between LiDAR and GNSS/INS (RTK) in the future? It is similar to the lidar2ins method in Opencalib, but the method in Opencalib has certain defects. It requires a large number of planar features in the environment, and the feature extraction part is for mechanical LiDAR, which is not suitable for solid-state LiDAR like Robosense M1P.
